services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./src/test/resources/script:/docker-entrypoint-initdb.d:ro
  job-service:
    build: .
    image: job-service
    ports:
      - "8080:8080"
    profiles:
      - deploy
    environment:
      SPRING_MONGODB_URI: mongodb://job_user:job_password@mongo:27017/job
    depends_on:
      - mongo
    restart: always