services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./src/test/resources/script:/docker-entrypoint-initdb.d:ro

  job-service-mock:
    image: mockserver/mockserver:latest
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init.json
    volumes:
      - ./src/test/resources/data/job-service.json:/config/init.json:ro

  candidate-service:
    build: .
    image: candidate-service
    ports:
      - "8080:8080"
    profiles:
      - deploy
    environment:
      SPRING_MONGODB_URI: mongodb://candidate_user:candidate_password@mongo:27017/candidate
      JOB_SERVICE_URL: http://job-service-mock:1080/job
    depends_on:
      - mongo
    restart: always